### ISSUE TITLE
Uncaught TypeError: CKEDITOR.tools.getUniqueId is not a function

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/CKEditor-Plugin#13]
Hi,

this happened in my Drupal installation. Once I click on the FREME Link button, the following error shows up in the console (from the notification plugin):

> Uncaught TypeError: CKEDITOR.tools.getUniqueId is not a function

You can check the complete log by trying it [here](http://waterpathogens.agroknow.gr/node/add/test).

**Comment by bjdmeest** [comment]
The notification plugin needs a ckeditor of at least 4.5. As far as I can see, the CKEditor version of http://waterpathogens.agroknow.gr/node/add/test is 4.4.3. However, this should result only in the not showing up of notifications.
The actual problem is that the FREME plugin has a dependency on jQuery. see https://github.com/freme-project/CKEditor-Plugin/blob/master/ckeditor/samples/freme.html#L10 for an example of how to do this.

I updated the readme to reflect the above, could you let me know whether this is sufficient?

**Comment by Katsivelisp** [comment]
Hello again,

thanks for the clarification, I configured the Drupal module to link at the latest CKEditor CDN. Now the notification plugin works fine.

However, I still get some errors regarding the API calls made when I click on the Link and Translate buttons. It seems to me that the URLs of the calls are missing a parameter (the "input" or "body" one) and the input text is wrongly appended at the end of the URL. Can you test this on the same URL I mentioned above?

**Comment by bjdmeest** [comment]
For some reason, the jquery library wasn't found, it should be fixed by fec7e844c4e58a0c217717047be6d6870a7481f1

Concerning the API calls: the e-internationalization server is currently having issues, see https://github.com/freme-project/e-services/issues/12

**Comment by Katsivelisp** [comment]
Hi again and thanks for your time.

I pulled the changes, but I still get the 400 "Bad request" error from FREME NER (after clicking the "Link" button). The call doesn't specify an input parameter.

**Comment by bjdmeest** [comment]
On http://waterpathogens.agroknow.gr/node/add/test ? I cannot see the changes of the latest pull reflected on that page.

**Comment by Katsivelisp** [comment]
Yes, I'm sorry. I had to clear the site cache. I can also see that errors change from browser to browser. In Firefox it seems to be a jQuery error, while in Chrome it seems to be a "Bad request" one.

**Comment by bjdmeest** [comment]
I have made a small update, I didn't erase the button icons, but create their paths now without duplicated slashes, maybe that improves the situation.

Concerning the API calls: I am afraid I have to wait until this is solved at the back-end. I re-opened the related issue at https://github.com/freme-project/Broker/issues/131. Once I have more info from there, I will report back here :).

PS: I am closing this issue, at it is no longer related to `CKEDITOR.tools.getUniqueId is not a function`. Feel free to open a new issue if needed :)

**Comment by bjdmeest** [comment]
As https://github.com/freme-project/e-services/issues/12 is now fixed, I assume the API call-errors should be resolved. @Katsivelisp, could you re-pull the changes and check again?

**Comment by Katsivelisp** [comment]
Hello again @bjdmeest. I am now getting a Linking Error on entity.js:149. In Chrome it seems like a Bad Request error again. You can view the full stack on the website.

**Comment by bjdmeest** [comment]
Hi, I currently do not get this error. The error might be caused because the api-dev of FREME might have been down. I do see that the default CSS styling is not included, I made a separate issue for this (#15)
